FROM python:3.12.6

WORKDIR /app

ADD . /app

RUN apt-get update

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV DOWNLOAD_PATH /app/Downloads

ENV NAME Backend

CMD ["python", "app.py"]  


